# Generated by Django 4.2.3 on 2023-10-12 12:47

from django.db import migrations, models
import pgvector.django


class Migration(migrations.Migration):

    dependencies = [
        ('text_bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_filename', models.CharField(max_length=100)),
                ('document_title', models.CharField(max_length=100)),
                ('embedding', pgvector.django.VectorField(dimensions=768)),
                ('text', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
