# Generated by Django 4.2.3 on 2023-10-12 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_bot', '0002_documentsplit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentsplit',
            old_name='document_filename',
            new_name='filename',
        ),
        migrations.RenameField(
            model_name='documentsplit',
            old_name='document_title',
            new_name='title',
        ),
        migrations.AddField(
            model_name='documentsplit',
            name='page',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
