# Generated by Django 4.2.3 on 2023-10-13 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_bot', '0003_rename_document_filename_documentsplit_filename_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentsplit',
            name='text_compression',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
