# Generated by Django 4.2.3 on 2023-10-13 14:43

from django.db import migrations
import pgvector.django


class Migration(migrations.Migration):

    dependencies = [
        ('text_bot', '0004_documentsplit_text_compression'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatquestion',
            name='embedding',
            field=pgvector.django.VectorField(dimensions=1536),
        ),
        migrations.AlterField(
            model_name='documentsplit',
            name='embedding',
            field=pgvector.django.VectorField(dimensions=1536),
        ),
    ]
