# Generated by Django 4.2.3 on 2023-10-13 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_bot', '0005_alter_chatquestion_embedding_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentsplit',
            name='text_compression',
            field=models.CharField(max_length=1000),
        ),
    ]
