# Generated by Django 4.2.3 on 2023-10-19 10:03

from django.db import migrations, models
import django.db.models.deletion
import pgvector.django


class Migration(migrations.Migration):

    dependencies = [
        ('text_bot', '0006_alter_documentsplit_text_compression'),
    ]

    operations = [
        migrations.CreateModel(
            name='CTDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_version', models.IntegerField()),
                ('document_title', models.CharField(max_length=100)),
                ('document_filename', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CTDocumentPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_page_text', models.CharField(max_length=5000)),
                ('document_page', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ct_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_pages', to='text_bot.ctdocument')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CTDocumentSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_title', models.CharField(max_length=100)),
                ('document_filename', models.CharField(max_length=100)),
                ('document_page', models.IntegerField()),
                ('split_text', models.CharField(max_length=1500)),
                ('split_text_compression', models.CharField(max_length=1500)),
                ('embedding', pgvector.django.VectorField(dimensions=1536)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ct_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_splits', to='text_bot.ctdocument')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.DeleteModel(
            name='DocumentSplit',
        ),
        migrations.AddIndex(
            model_name='ctdocumentsplit',
            index=pgvector.django.IvfflatIndex(fields=['embedding'], lists=100, name='my_index', opclasses=['vector_l2_ops']),
        ),
    ]
