# Generated by Django 4.2.3 on 2023-10-19 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_bot', '0007_ctdocument_ctdocumentpage_ctdocumentsplit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctdocumentpage',
            name='document_page_text',
            field=models.CharField(max_length=25000),
        ),
    ]
