# Generated by Django 4.2.3 on 2023-10-19 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_bot', '0008_alter_ctdocumentpage_document_page_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctdocumentpage',
            name='document_page_text',
            field=models.CharField(max_length=6000),
        ),
    ]
