# Generated by Django 4.2.3 on 2023-10-20 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_bot', '0009_alter_ctdocumentpage_document_page_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ctdocumentpage',
            old_name='document_page',
            new_name='document_page_number',
        ),
        migrations.AddField(
            model_name='ctdocumentsplit',
            name='split_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
