# Generated by Django 4.2.6 on 2023-10-27 08:33

from django.db import migrations
import pgvector.django


class Migration(migrations.Migration):

    dependencies = [
        ('text_bot', '0010_rename_document_page_ctdocumentpage_document_page_number_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='ctdocumentsplit',
            name='my_index',
        ),
        migrations.AddIndex(
            model_name='ctdocumentsplit',
            index=pgvector.django.IvfflatIndex(fields=['embedding'], lists=100, name='my_index', opclasses=['vector_cosine_ops']),
        ),
        migrations.AddIndex(
            model_name='ctdocumentsplit',
            index=pgvector.django.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='my_hnsw_index', opclasses=['vector_l2_ops']),
        ),
    ]
