# Generated by Django 4.2.6 on 2023-11-17 16:46

from django.db import migrations, models
import django.db.models.deletion
import pgvector.django


class Migration(migrations.Migration):

    dependencies = [
        ('text_bot', '0011_remove_ctdocumentsplit_my_index_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CTDocumentSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_title', models.CharField(max_length=100)),
                ('document_filename', models.CharField(max_length=100)),
                ('document_page', models.IntegerField()),
                ('section_title', models.CharField(max_length=100)),
                ('section_text', models.CharField(max_length=1500)),
                ('section_content_summary', models.CharField(max_length=1500)),
                ('section_references', models.CharField(max_length=1500)),
                ('section_topics', models.CharField(max_length=1500)),
                ('section_number', models.IntegerField()),
                ('title_embedding', pgvector.django.VectorField(dimensions=1536)),
                ('text_embedding', pgvector.django.VectorField(dimensions=1536)),
                ('content_summary_embedding', pgvector.django.VectorField(dimensions=1536)),
                ('references_embedding', pgvector.django.VectorField(dimensions=1536)),
                ('topics_embedding', pgvector.django.VectorField(dimensions=1536)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CTDocumentSubsection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_title', models.CharField(max_length=100)),
                ('document_filename', models.CharField(max_length=100)),
                ('document_page', models.IntegerField()),
                ('subsection_title', models.CharField(max_length=100)),
                ('subsection_text', models.CharField(max_length=1500)),
                ('subsection_content_summary', models.CharField(max_length=1500)),
                ('subsection_references', models.CharField(max_length=1500)),
                ('subsection_topics', models.CharField(max_length=1500)),
                ('subsection_number', models.IntegerField()),
                ('title_embedding', pgvector.django.VectorField(dimensions=1536)),
                ('text_embedding', pgvector.django.VectorField(dimensions=1536)),
                ('content_summary_embedding', pgvector.django.VectorField(dimensions=1536)),
                ('references_embedding', pgvector.django.VectorField(dimensions=1536)),
                ('topics_embedding', pgvector.django.VectorField(dimensions=1536)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.RenameIndex(
            model_name='ctdocumentsplit',
            new_name='document_ivf_flat_index',
            old_name='my_index',
        ),
        migrations.RenameIndex(
            model_name='ctdocumentsplit',
            new_name='document_hnsw_index',
            old_name='my_hnsw_index',
        ),
        migrations.AddField(
            model_name='ctdocumentsubsection',
            name='ct_document_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_subsections', to='text_bot.ctdocumentsection'),
        ),
        migrations.AddField(
            model_name='ctdocumentsection',
            name='ct_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_sections', to='text_bot.ctdocument'),
        ),
        migrations.AddIndex(
            model_name='ctdocumentsubsection',
            index=pgvector.django.IvfflatIndex(fields=['title_embedding', 'text_embedding', 'content_summary_embedding', 'references_embedding', 'topics_embedding'], lists=100, name='document_subsection_ivf_flat_index', opclasses=['vector_cosine_ops', 'vector_cosine_ops', 'vector_cosine_ops', 'vector_cosine_ops', 'vector_cosine_ops']),
        ),
        migrations.AddIndex(
            model_name='ctdocumentsubsection',
            index=pgvector.django.HnswIndex(ef_construction=64, fields=['title_embedding', 'text_embedding', 'content_summary_embedding', 'references_embedding', 'topics_embedding'], m=16, name='document_subsection_hnsw_index', opclasses=['vector_l2_ops', 'vector_l2_ops', 'vector_l2_ops', 'vector_l2_ops', 'vector_l2_ops']),
        ),
        migrations.AddIndex(
            model_name='ctdocumentsection',
            index=pgvector.django.IvfflatIndex(fields=['title_embedding', 'text_embedding', 'content_summary_embedding', 'references_embedding', 'topics_embedding'], lists=100, name='document_section_ivf_flat_index', opclasses=['vector_cosine_ops', 'vector_cosine_ops', 'vector_cosine_ops', 'vector_cosine_ops', 'vector_cosine_ops']),
        ),
        migrations.AddIndex(
            model_name='ctdocumentsection',
            index=pgvector.django.HnswIndex(ef_construction=64, fields=['title_embedding', 'text_embedding', 'content_summary_embedding', 'references_embedding', 'topics_embedding'], m=16, name='document_section_hnsw_index', opclasses=['vector_l2_ops', 'vector_l2_ops', 'vector_l2_ops', 'vector_l2_ops', 'vector_l2_ops']),
        ),
    ]
